### ISSUE TITLE
Add comment on pin numbering system.

### ISSUE THREAD

**Issue by itrobinson** [the-raspberry-pi-guy/OLED#1]
In the Python examples (```OLEDclock.py```, ```OLEDimage.py```, ```OLEDip.py``` and ```OLEDtext.py```) it would be useful to have a more detailed comment about the numbering of the reset and DC pins. (By the way, what does DC mean?)

Change:

```python
# Sets up our pins again
RESET_PIN = 15
DC_PIN    = 16
```

to:

```python
# Define which GPIO pins the reset (RST) and DC signals on the OLED display are connected to on the
# Raspberry Pi. The defined pin numbers must use the WiringPi pin numbering scheme.
RESET_PIN = 15 # WiringPi pin 15 is GPIO14.
DC_PIN = 16 # WiringPi pin 16 is GPIO15.
```

**Comment by the-raspberry-pi-guy** [comment]
Of course, excellent edition that I will now change.

A quick look at the datasheet (https://www.adafruit.com/datasheets/SSD1306.pdf) for the display shows that DC is the Data/Command control pin: 

"This is Data/Command control pin. When it is pulled HIGH (i.e. connect to VDD), the data
at D[7:0] is treated as data. When it is pulled LOW, the data at D[7:0] will be transferred
to the command register.
In I2
C mode, this pin acts as SA0 for slave address selection.
When 3-wire serial interface is selected, this pin must be connected to VSS."

**Comment by the-raspberry-pi-guy** [comment]
Comments are now changed to include your detail. Issue resolved!
