### ISSUE TITLE
TypeError: __init__() takes at least 3 arguments (3 given)

### ISSUE THREAD

**Issue by Wizam7** [the-raspberry-pi-guy/OLED#2]
Hello, I have an Adafruit_SSD1306 128x32 SPI connected to a raspberry Pi3, am a beginner with those things actually, anyway I downloaded and installed the Software and followed the video: [https://www.youtube.com/watch?v=BeBfpJnN9SE&feature=c4-overview&list=UUfY8sl5Q6VKndz0nLaGygPw](url) but at at the end I keep getting this error msg and can't get my display working:
`Traceback (most recent call last):
  File "OLEDclock.py", line 18, in <module>
    led = gaugette.ssd1306.SSD1306(dc_pin=DC_PIN, reset_pin=RESET_PIN)
TypeError: __init__() takes at least 3 arguments (3 given)
`
I hope its not a repeated question/issue cuz i searched a lot and couldn't find a solution for it.
By the way I had it working before on the same device with the same display but after I formatted the SD and installed a fresh Linux Rasbian then it didn't work anymore, also I got this other one and its working [https://github.com/adafruit/Adafruit_SSD1306](url) but I need the OLEDclock.py to work, so i can use it for the pi that works as Stratum NTP Server.
Any help is appreciated
Thanks in advance.

**Comment by the-raspberry-pi-guy** [comment]
Hi there,

Have you modified the code at all? What version of Python are you running my code with?

Also, what example works in the Adafruit_SSD1306 code? Can you link me that directly? Then I can compare the OLEDclock.py code.

I wrote this code some time ago, and so it wouldn't surprise me if some library update here or some other change has 'broken' the code.

Thanks

**Comment by Wizam7** [comment]
Hi there,

Thanks for the quick replay! I haven't modified the code, it's the same, tried few things like changing the pins but that didn't effect and think it's not needed cuz as you said maybe its just some update that broke the code.
The Python version is Python 2.7.9.

The example that works in the Adafruit_SSD1306 code is:
 [https://github.com/adafruit/Adafruit_Python_SSD1306/blob/master/examples/shapes.py](url)
of course I had to change the pins there and uncomment line 46 and comment 58.

Thanks

**Comment by the-raspberry-pi-guy** [comment]
OK that uses a different library to the one that my code is using (py-gaugette). From what I can see online: https://github.com/guyc/py-gaugette there may have been an update that has broken functionality with old code (how helpful).

I am in the middle of my exam season here and so don't have time to wire up the circuit and fiddle around with the code at the moment. My suggestion would be to read through the changes on py-gaugette's GitHub page, and then just fiddle with my clock code?

Also note: I did not write that code. Whilst I wrote the other programs in this directory, that particular one came as an example with py-gaugette. It seems that it has been updated to use the new syntax/update. Take a look here: https://github.com/guyc/py-gaugette/blob/master/samples/ssd1306_test.py

Any-which-way: if you solve the issue, would you mind submitting a pull request and I can update this code?

**Comment by Wizam7** [comment]
Ok! 
Yea, that one uses Adafruit_SSD1306 library.

Well, thanks a lot for the help, I will try and if I get any good results then I will update you and submit a pull request.

A lot of success with the exams!

**Comment by the-raspberry-pi-guy** [comment]
No problem, I hope to get a PR from you soon.

I'll leave this issue open for now as it is still unresolved, if you have anymore questions I'll try to answer them

**Comment by Wizam7** [comment]
Alright! Cool, thanks!

**Comment by the-raspberry-pi-guy** [comment]
Thanks to the hard work of Wizam7, the OLED code has been updated/in the process of being updated. Please open another issue if these fixes don't resolve any issue you are having!
